name: Docker login, push container image to ACR and scan container image using Trivy
on:
  push:
    branches:
      - main
permissions:
  contents: write
env:
 REGISTRY: ghcr.io
 IMAGE_NAME: assignments-base
jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.PTOKEN_GITHUB }}
       
    - name: Build and Push images 
      uses: docker/build-push-action@v2
      
      with:
        push: true
        tags: latest
        images: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}

    - name: Run Trivy vulnerability scanning
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:latest'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'