name: Docker login, push container image to ACR and scan container image using Trivy
on:
  push:
    branches:
      - main
env:
 IMAGE_NAME: assignments-base
jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
    - name: Log into registry
      uses: docker/login-action@v1
      with:
       registry: ${{ secrets.ACR_ENDPOINT }}
       username: ${{ secrets.ACR_USERNAME }}
       password: ${{ secrets.ACR_PASSWORD }}
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Build and Push images 
      uses: docker/build-push-action@v2
      
      with:
        push: true
        tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }} 

    - name: Run Trivy vulnerability scanning
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
