name: Create and publish a Docker image
on:
  push:
    branches: 
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: demo-repository
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tag_with_sha: true
          tags: ghcr.io/nextgen-dx-catalyst/demo-repository:${{ github.sha }} 
          labels: ${{ steps.meta.outputs.labels }}
          add_git_labels: true
      - name: Run Trivy vulnerability scanning
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/nextgen-dx-catalyst/demo-repository:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
