name: trivy-scanning
on:
  push:
    branches:
      - main
  pull_request:
permissions: write-all
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/nextgen-dx-catalyst/demo:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/nextgen-dx-catalyst/demo:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'


          
